name: herdnet
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pip
  - setuptools
  - wheel
  - pytorch
  - torchvision
  - numpy
  - requests
  - pyyaml
  - pillow
  - certifi
  - openssl
  - pip:
    # Core ML/CV packages - updated for Python 3.12 compatibility
    - albumentations>=1.3.0
    - opencv-python>=4.8.0
    - opencv-python-headless>=4.8.0
    - scikit-image>=0.21.0
    - scikit-learn>=1.3.0
    - scipy>=1.11.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - pandas>=2.0.0
    - imageio>=2.31.0
    - imgaug>=0.4.0

    # Hydra for config management
    - hydra-core>=1.3.0
    - omegaconf>=2.3.0

    # WandB for experiment tracking - updated version
    - wandb>=0.15.0

    # FiftyOne (optional - skip if not needed, or use latest)
    # - fiftyone>=0.21.0
    # - fiftyone-brain>=0.21.0

    # Utilities
    - tqdm>=4.65.0
    - click>=8.1.0
    - pyyaml>=6.0
    - pillow>=10.0.0
    - jinja2>=3.1.0
    - python-dateutil>=2.8.0
    - pytz
    - tabulate>=0.9.0
    - xmltodict>=0.13.0

    # Async/networking
    - aiofiles>=23.0.0
    - httpx>=0.24.0
    - requests>=2.31.0

    # Scientific computing
    - shapely>=2.0.0
    - networkx>=3.0

    # Git/version control
    - gitpython>=3.1.0

    # Other dependencies (relaxed versions for compatibility)
    - deprecated
    - dill
    - psutil
    - wrapt
    - sortedcontainers
    - retrying